import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My awesome site",
  description: "Generated by NextJS + Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
